---

- block:
    - name: save redis_password
      copy:
        content: "{{ redis_password }}"
        dest: "{{ redis_password_save }}"
        mode: "0600"
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"

  when: redis_password is defined

- block:
    - name: check redis_password_save file
      stat:
        path: "{{ redis_password_save }}"
      register: t_redis_password_save

    - block:
        - name: generate redis password
          command: apg -m 30 -n 1
          register: t_redis_password

        - name: save to redis_password_save
          copy:
            content: "{{ t_redis_password.stdout }}"
            dest: "{{ redis_password_save }}"
            mode: "0600"
            owner: "{{ redis_user }}"
            group: "{{ redis_group }}"
      when: not t_redis_password_save.stat.exists

    - name: reload redis_password
      command: " cat {{ redis_password_save }}"
      changed_when: no
      register: t_redis_password

    - name: set redis_password
      set_fact:
        redis_password: "{{ t_redis_password.stdout }}"

  when: redis_password is not defined


- name: deploy redis.conf
  template:
    src: conf/redis.conf
    dest: "{{ redis_conf }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: "0600"
  register: t_redis_conf_deploy
